services:
  db:
    image: mysql:8.0
    container_name: app_db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_api
    restart: unless-stopped
    env_file: .env
    working_dir: /usr/src/app
    environment:
      DB_HOST: "db"
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/app
    command: ["npm", "run", "dev"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app_web
    restart: unless-stopped
    env_file: .env
    working_dir: /usr/src/app
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  db_data:
