export enum AbilityName {
  Java = 'Java',
  NodeJS = 'Node.js',
  CPP = 'C++',
  PHP = 'PHP',
  Python = 'Python',
  Go = 'Go',
  ADVPL = 'ADVPL',
  Angular = 'Angular',
  Electron = 'Electron',
  React = 'React',
  ReactNative = 'ReactNative',
  MongoDB = 'MongoDB',
  MySQL = 'MySQL',
  SQLServer = 'SQLServer',
  Postgres = 'Postgres',
  Backend = 'Backend',
  FrontEnd = 'FrontEnd',
}
